### ISSUE TITLE
Sort indicator style issues with multi-column sorting

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-themes#1832]
**Describe the bug**
The sort indicators (numbers) are misaligned in Bootstrap theme when multi-column sorting is used ([react](https://www.telerik.com/kendo-react-ui/components/grid/sorting/#toc-customize-sorting)) and the indicator styles differ from the design for Default and Material themes.

**To reproduce**

1. Go to https://www.telerik.com/kendo-react-ui/components/grid/sorting/#toc-customize-sorting
2. Click on the "Enable multiple columns sorting" checkbox
3. Sort multiple columns by clicking on their header, e.g. "Product ID" and "Product Name"

**Expected behavior**
- The sort indicator is not misaligned:
Bootstrap
![image](https://user-images.githubusercontent.com/1857705/92464609-0f499f80-f1d6-11ea-9bae-ebb8c2f0f0bf.png)
Default
![image](https://user-images.githubusercontent.com/1857705/92464671-22f50600-f1d6-11ea-9c6a-40a630ad57da.png)
- the implementation of the colors is according to the design:
Default
![image](https://user-images.githubusercontent.com/1857705/92464671-22f50600-f1d6-11ea-9c6a-40a630ad57da.png)
Material
![image](https://user-images.githubusercontent.com/1857705/92464758-46b84c00-f1d6-11ea-9d5d-2b0155d87f67.png)

**Screenshots**

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
Found as part of https://github.com/telerik/blazor/issues/1384#issuecomment-688746728

**Comment by PreslavKozovski** [comment]
This should be fixed together with https://github.com/telerik/kendo-themes/issues/410 when https://github.com/telerik/k2/issues/280 is closed

**Comment by joneff** [comment]
@Stamo-Gochev please check #410 and the rendering in telerik/k2#280 if this is fixed. Granted, there is modification to be made, but the change is backwards compatible e.g. the new styles only apply with new rendering.

**Comment by joneff** [comment]
Closed with #410

**Comment by Stamo-Gochev** [comment]
@joneff 
- the new styles are working fine with the current (old) version of the rendering in the same way as before
- the new styles are working fine with the new version of the rendering in blazor - https://github.com/telerik/blazor/issues/1887#issuecomment-747906544

**Comment by dtopuzov** [comment]
Looks like we still have some deviations in bootstrap and Blazor:

https://github.com/telerik/blazor/issues/1887#issuecomment-767396592
